PolyhedralDev/Terra

build.gradle.kts
src/main/java/com/dfsek/terra/EventListener.java
src/main/java/com/dfsek/terra/async/AsyncStructureFinder.java
src/main/java/com/dfsek/terra/carving/Cavern.java
src/main/java/com/dfsek/terra/carving/UserDefinedCarver.java
src/main/java/com/dfsek/terra/command/OreCommand.java
src/main/java/com/dfsek/terra/config/genconfig/FloraConfig.java
src/main/java/com/dfsek/terra/config/genconfig/PaletteConfig.java
src/main/java/com/dfsek/terra/config/genconfig/biome/BiomeOceanConfig.java
src/main/java/com/dfsek/terra/config/genconfig/biome/BiomePaletteConfig.java
src/main/java/com/dfsek/terra/config/genconfig/biome/BiomeSlabConfig.java
src/main/java/com/dfsek/terra/population/StructurePopulator.java
src/main/java/com/dfsek/terra/procgen/GridSpawn.java
src/main/java/com/dfsek/terra/structure/features/EntityFeature.java
src/main/java/com/dfsek/terra/util/DataUtil.java

XoRoShiRo128PlusRandom is a Faster Random Class that is many times faster than the native Java Random. It also features better random distribution and the ability to be split and retain the exact same noise output like the native SplitableRandom.
http://dsiutils.di.unimi.it/docs/it/unimi/dsi/util/XoRoShiRo128PlusRandom.html

Use Faster XoRoShiRo128PlusRandom

---

src/main/java/com/dfsek/terra/population/FloraPopulator.java
src/main/java/com/dfsek/terra/procgen/GridSpawn.java
src/main/java/com/dfsek/terra/procgen/voxel/VoxelGeometry.java
src/main/java/com/dfsek/terra/structure/features/EntityFeature.java
src/main/java/com/dfsek/terra/util/GlueList.java
src/test/java/LookupGenerator.java

Uses GlueList a faster List implementation. Drop in replacement for ArrayList.
https://github.com/ertugrulcetin/GlueList

Use Faster GlueList

---

.github/workflows/build.yml

Will also release the built jar.

Github action to build on tag matching  regex v.*

---

src/main/java/com/dfsek/terra/generation/items/ores/DeformedSphereOre.java
src/main/java/com/dfsek/terra/generation/items/ores/Ore.java
src/main/java/com/dfsek/terra/generation/items/ores/VanillaOre.java

added vanilla ores + 2 properties to the default ore that's required by all ores.

Vanilla ore

---

build.gradle.kts

This PR changes how ProcessResources is handled. I think currently it's not being called properly which is why the packs don't download on the first build. This changes it to ensure that process resources runs on compile and requires shadowJar to depend upon downloading the pack first.
Fixes #26

Implemented alternative ProcessResources

---

common/src/main/java/com/dfsek/terra/api/GenericLoaders.java
common/src/main/java/com/dfsek/terra/api/math/ProbabilityCollection.java
common/src/main/java/com/dfsek/terra/api/math/noise/samplers/FastNoiseLite.java
common/src/main/java/com/dfsek/terra/api/math/noise/samplers/LinearNormalizer.java
common/src/main/java/com/dfsek/terra/api/math/noise/samplers/Normalizer.java
common/src/main/java/com/dfsek/terra/api/world/palette/NoisePalette.java
common/src/main/java/com/dfsek/terra/api/world/palette/Palette.java
common/src/main/java/com/dfsek/terra/api/world/palette/RandomPalette.java
common/src/main/java/com/dfsek/terra/api/world/tree/fractal/TreeGeometry.java
common/src/main/java/com/dfsek/terra/api/world/tree/fractal/trees/OakTree.java
common/src/main/java/com/dfsek/terra/api/world/tree/fractal/trees/ShatteredTree.java
common/src/main/java/com/dfsek/terra/api/world/tree/fractal/trees/SmallShatteredTree.java
common/src/main/java/com/dfsek/terra/api/world/tree/fractal/trees/SpruceTree.java
common/src/main/java/com/dfsek/terra/biome/palette/SinglePalette.java
common/src/main/java/com/dfsek/terra/config/factories/PaletteFactory.java
common/src/main/java/com/dfsek/terra/config/loaders/config/FloraLayerLoader.java
common/src/main/java/com/dfsek/terra/config/loaders/config/NoiseBuilderLoader.java
common/src/main/java/com/dfsek/terra/config/loaders/config/TreeLayerLoader.java
common/src/main/java/com/dfsek/terra/config/templates/PaletteTemplate.java
common/src/main/java/com/dfsek/terra/generation/MasterChunkGenerator.java
common/src/main/java/com/dfsek/terra/generation/config/NoiseBuilder.java
common/src/main/java/com/dfsek/terra/population/FloraPopulator.java
common/src/main/java/com/dfsek/terra/population/TreePopulator.java
common/src/main/java/com/dfsek/terra/population/items/PlaceableLayer.java
common/src/main/java/com/dfsek/terra/population/items/flora/FloraLayer.java
common/src/main/java/com/dfsek/terra/population/items/flora/TerraFlora.java
common/src/main/java/com/dfsek/terra/population/items/tree/TreeLayer.java

Adds noise-related config:
* Ability to configure lookup functions
* Ability to use custom functions for palettes
* Ability to use custom functions for Flora/Tree placement
* Fast white noise algorithm used for palettes and flora/trees.

Noise config additions

---

build.gradle.kts
common/src/main/java/com/dfsek/terra/api/core/TerraPlugin.java
common/src/main/java/com/dfsek/terra/api/core/event/TerraEventManager.java
common/src/main/java/com/dfsek/terra/api/core/event/annotations/Listener.java
common/src/main/java/com/dfsek/terra/api/core/event/events/config/ConfigPackLoadEvent.java
common/src/main/java/com/dfsek/terra/api/core/event/events/config/ConfigPackPostLoadEvent.java
common/src/main/java/com/dfsek/terra/api/core/event/events/config/ConfigPackPreLoadEvent.java
common/src/main/java/com/dfsek/terra/api/core/event/events/world/TerraWorldLoadEvent.java
common/src/main/java/com/dfsek/terra/api/structures/script/StructureScript.java
common/src/main/java/com/dfsek/terra/api/util/ReflectionUtil.java
common/src/main/java/com/dfsek/terra/config/pack/ConfigPack.java
common/src/main/java/com/dfsek/terra/registry/FunctionRegistry.java
common/src/main/java/com/dfsek/terra/registry/TerraRegistry.java
common/src/main/java/com/dfsek/terra/world/TerraWorld.java
common/src/test/java/biome/DistributionTest.java
common/src/test/java/event/EventTest.java
platforms/bukkit/src/main/java/com/dfsek/terra/bukkit/TerraBukkitPlugin.java
platforms/fabric/src/main/java/com/dfsek/terra/fabric/TerraFabricPlugin.java
platforms/region/src/main/java/com/dfsek/terra/StandalonePlugin.java

Implements an event system and allows registration of TerraScript functions.

Function Registry and Event System

---

common/src/main/java/com/dfsek/terra/world/population/FloraPopulator.java
common/src/main/java/com/dfsek/terra/world/population/OrePopulator.java
common/src/main/java/com/dfsek/terra/world/population/StructurePopulator.java
common/src/main/java/com/dfsek/terra/world/population/TreePopulator.java

Fixed populator disable config (#130)

---

common/src/main/java/com/dfsek/terra/world/population/FloraPopulator.java
common/src/main/java/com/dfsek/terra/world/population/OrePopulator.java
common/src/main/java/com/dfsek/terra/world/population/StructurePopulator.java
common/src/main/java/com/dfsek/terra/world/population/TreePopulator.java
platforms/fabric/src/main/java/com/dfsek/terra/fabric/TerraFabricPlugin.java
platforms/fabric/src/main/java/com/dfsek/terra/fabric/world/generator/FabricChunkGeneratorWrapper.java

Fix minor Fabric issues

---

common/src/main/java/com/dfsek/terra/api/util/world/PaletteUtil.java
common/src/main/java/com/dfsek/terra/api/world/palette/slant/SlantHolder.java
common/src/main/java/com/dfsek/terra/config/GenericLoaders.java
common/src/main/java/com/dfsek/terra/config/builder/GeneratorBuilder.java
common/src/main/java/com/dfsek/terra/config/builder/UserDefinedBiomeBuilder.java
common/src/main/java/com/dfsek/terra/config/loaders/palette/slant/SlantHolderLoader.java
common/src/main/java/com/dfsek/terra/config/templates/BiomeTemplate.java
common/src/main/java/com/dfsek/terra/world/generation/WorldGenerator.java

Implement multiple slant thresholds (#91)

---

build.gradle.kts
buildSrc/src/main/kotlin/com/dfsek/terra/CommonConfig.kt
buildSrc/src/main/kotlin/com/dfsek/terra/CompilationConfig.kt
buildSrc/src/main/kotlin/com/dfsek/terra/DependencyConfig.kt
buildSrc/src/main/kotlin/com/dfsek/terra/DistributionConfig.kt
common/build.gradle.kts
gradle.properties
settings.gradle.kts

The current gradle performance is sub-par and could be improved easily by allowing for multithreading.
Fix #142

Improve gradle performance significantly

---

platforms/fabric/src/main/java/com/dfsek/terra/fabric/generation/FabricChunkGeneratorWrapper.java

Override structure location on Fabric

---

platforms/fabric/build.gradle.kts
platforms/fabric/src/main/java/com/dfsek/terra/fabric/TerraFabricPlugin.java
platforms/fabric/src/main/java/com/dfsek/terra/fabric/mixin/CommandManagerMixin.java
platforms/fabric/src/main/resources/fabric.mod.json
platforms/fabric/src/main/resources/terra.mixins.json

Removes dependency on Fabric API

Remove dependency on Fabric API

---

common/src/main/resources/lang/cs_cz.yml

I've created a new localization file for Czech language

Creating new locale for Czech

---

build.gradle.kts
common/build.gradle.kts
common/src/main/java/com/dfsek/terra/commands/biome/BiomeInfoCommand.java
common/src/main/java/com/dfsek/terra/config/templates/BiomeTemplate.java

Bumps Tectonic version to allow multi-inheritance in all abstractable configs.
List loaders can now accept singletons. This means that all existing `extends` keys will just be read as singleton lists and treated exactly the same as previously.
project.

Implement multi-inheritance in configs

---

build.gradle.kts
common/src/main/java/com/dfsek/terra/world/TerraWorld.java
platforms/fabric/src/main/java/com/dfsek/terra/fabric/TerraFabricPlugin.java
platforms/fabric/src/main/java/com/dfsek/terra/fabric/event/BiomeRegistrationEvent.java
platforms/fabric/src/main/java/com/dfsek/terra/fabric/event/GameInitializationEvent.java
platforms/fabric/src/main/java/com/dfsek/terra/fabric/generation/FabricChunkGeneratorWrapper.java
platforms/fabric/src/main/java/com/dfsek/terra/fabric/generation/TerraGeneratorType.java
platforms/fabric/src/main/java/com/dfsek/terra/fabric/mixin/GeneratorOptionsMixin.java
platforms/fabric/src/main/java/com/dfsek/terra/fabric/mixin/lifecycle/client/MinecraftClientMixin.java
platforms/fabric/src/main/java/com/dfsek/terra/fabric/mixin/lifecycle/package-info.java
platforms/fabric/src/main/java/com/dfsek/terra/fabric/mixin/lifecycle/server/GeneratorOptionsMixin.java
platforms/fabric/src/main/java/com/dfsek/terra/fabric/mixin/lifecycle/server/ServerMainMixin.java
platforms/fabric/src/main/java/com/dfsek/terra/fabric/util/FabricUtil.java
platforms/fabric/src/main/java/com/dfsek/terra/fabric/util/ProtoBiome.java
platforms/fabric/src/main/resources/terra.mixins.json

We are really good at breaking getHeight.   
This PR fixes `getHeight` and improves `getColumnSample`. It also initializes biomes later (at world load rather than at game load) so modifications applied to Vanilla biomes using the Fabric Biome Modification API get applied to Terra biomes as well.
Fixes #212
Fixes #214 
Fixes #197 
project.

Inject biomes later, fix getHeight issues (again)

---

platforms/bukkit/build.gradle.kts
platforms/bukkit/src/main/java/com/dfsek/terra/bukkit/world/BukkitWorld.java

bump Paper API, implement custom world height on Bukkit.
project.

Bump Paper API version to 1.17, implement custom world height support on Bukkit.

---

platforms/bukkit/src/main/java/com/dfsek/terra/bukkit/TerraBukkitPlugin.java

add V1_17 to Bukkit versions (forgot to do that in #221)
project.

bukkit version 1_17

---

common/implementation/src/main/java/com/dfsek/terra/registry/config/ConfigTypeRegistry.java
common/implementation/src/main/java/com/dfsek/terra/registry/config/FloraRegistry.java

Removes 'included flora' entries from the flora registry 
Part of #227 change list
Requires pack developers to use pack defined or otherwise flora registry entries, rather than using 'included flora'. Any prior packs using 'included flora' will need to reimplement the required entries in order to load correctly.
project.

Remove hardcoded flora registry entries

---

common/src/main/java/com/dfsek/terra/api/util/JarUtil.java
platforms/fabric/src/main/java/com/dfsek/terra/fabric/TerraFabricPlugin.java

This PR fixes a crash when using Terra in the workspace of other mods. 
https://paste.ubuntu.com/p/gZxVn4vh3p/
project.

Fix fabric development environment launch

---

common/src/main/resources/lang/de_de.yml

This fixes a few typos or miss spelled words in the german translation.
This fixes a few typos.

Fix spelling issues / typos in german translation

---

platforms/bukkit/src/main/java/com/dfsek/terra/bukkit/world/BukkitTree.java

This mitigates https://github.com/PaperMC/Paper/issues/6028 by try-catching tree generation. 
This fixes server crash caused by tree generation issue in Paper.
This prevents the tree generation bug from crashing the server. 
project.

Mitigate issues with tree generation in paper

---

.gitignore

Update the gitignore file because it not ignoring the .idea folder annoyed me
project.

Update gitignore file to ignore a few things that annoyed me

---

common/implementation/src/main/java/com/dfsek/terra/config/pack/ConfigPackImpl.java

replace win path delimiter to linux-like for meta config laoder

fix win loading

---

common/api/core/src/main/java/com/dfsek/terra/api/config/PluginConfig.java
common/implementation/src/main/java/com/dfsek/terra/config/PluginConfigImpl.java

Remove debug logging config value as it is no longer needed with the SLF4J api.
project.

Remove debug logging config value

---

common/addons/config-locators/src/main/java/com/dfsek/terra/addons/feature/locator/config/GaussianRandomLocatorTemplate.java
common/addons/config-locators/src/main/java/com/dfsek/terra/addons/feature/locator/config/RandomLocatorTemplate.java

Allows metaconfig of some locator keys
project.

Add missing meta annotations to locators

---

common/addons/biome-provider-pipeline/src/main/java/com/dfsek/terra/addons/biome/pipeline/BiomePipelineAddon.java
common/addons/biome-provider-pipeline/src/main/java/com/dfsek/terra/addons/biome/pipeline/config/BiomeProviderTemplate.java
common/addons/biome-provider-pipeline/src/main/java/com/dfsek/terra/addons/biome/pipeline/config/SamplerSourceTemplate.java
common/addons/biome-provider-pipeline/src/main/java/com/dfsek/terra/addons/biome/pipeline/config/stage/StageTemplate.java
common/addons/biome-provider-pipeline/src/main/java/com/dfsek/terra/addons/biome/pipeline/source/SamplerSource.java
common/addons/chunk-generator-noise-3d/src/main/java/com/dfsek/terra/addons/chunkgenerator/config/noise/BiomeNoiseConfigTemplate.java
common/addons/config-distributors/src/main/java/com/dfsek/terra/addons/feature/distributor/DistributorAddon.java
common/addons/config-distributors/src/main/java/com/dfsek/terra/addons/feature/distributor/config/SamplerDistributorTemplate.java
common/addons/config-distributors/src/main/java/com/dfsek/terra/addons/feature/distributor/distributors/SamplerDistributor.java
common/addons/config-locators/src/main/java/com/dfsek/terra/addons/feature/locator/LocatorAddon.java
common/addons/config-locators/src/main/java/com/dfsek/terra/addons/feature/locator/config/Sampler3DLocatorTemplate.java
common/addons/config-locators/src/main/java/com/dfsek/terra/addons/feature/locator/config/SamplerLocatorTemplate.java
common/addons/config-locators/src/main/java/com/dfsek/terra/addons/feature/locator/locators/Sampler3DLocator.java
common/addons/config-locators/src/main/java/com/dfsek/terra/addons/feature/locator/locators/SamplerLocator.java
common/addons/config-noise-function/src/main/java/com/dfsek/terra/addons/noise/NoiseConfigPackTemplate.java
common/addons/config-noise-function/src/main/java/com/dfsek/terra/addons/noise/config/templates/DomainWarpTemplate.java
common/addons/config-noise-function/src/main/java/com/dfsek/terra/addons/noise/config/templates/KernelTemplate.java
common/addons/config-noise-function/src/main/java/com/dfsek/terra/addons/noise/config/templates/noise/fractal/FractalTemplate.java
common/addons/config-noise-function/src/main/java/com/dfsek/terra/addons/noise/config/templates/normalizer/NormalizerTemplate.java
common/addons/config-palette/src/main/java/com/dfsek/terra/addons/palette/PaletteTemplate.java
common/addons/config-palette/src/main/java/com/dfsek/terra/addons/palette/palette/PaletteLayerLoader.java

Renames various config keys and registry entries to maintain more consistent conventions. This mainly renames keys and registry entries using terms 'function' and 'noise' to the term 'sampler'.
- `noise` to `samplers` in pack manifest. 
- `function` to `sampler` in sampler parameters that take a sampler. 
- `noise` to `sampler` in palette configs. 
- `blend.noise` to `blend.sampler` in pipeline configs.
- `noise` to `sampler` in pipeline stage configs.
- Rename pipeline `NoiseSource` to `SamplerSource` + registry key `NOISE` to `SAMPLER`
- Changes to most `BiomeNoiseConfigTemplate` key names:
- `noise` to `terrain.sampler`
- `elevation.equation` to `terrain.sampler-2d`
- Keys under `blend` placed under …

Key name refactor

---

common/addons/config-noise-function/src/main/java/com/dfsek/terra/addons/noise/NoiseConfigPackTemplate.java

Makes declaring global samplers optional, as it is not essential for a pack to function.
project.

Make pack manifest `samplers` key optional

---

common/implementation/base/src/main/java/com/dfsek/terra/config/pack/ConfigPackTemplate.java

Title, `stages` is not required for a pack to load and can be made optional.
project.

Make pack manifest `stages` key optional

---

common/addons/config-noise-function/src/main/java/com/dfsek/terra/addons/noise/NoiseAddon.java
common/addons/config-noise-function/src/main/java/com/dfsek/terra/addons/noise/config/templates/normalizer/PosterizationNormalizerTemplate.java
common/addons/config-noise-function/src/main/java/com/dfsek/terra/addons/noise/normalizer/PosterizationNormalizer.java

Added a Normalizer to posterize the input function, i.e. separate it into "steps" with discrete values.
Closes #204 
change 
project.

Implement posterization normalizer

---

platforms/fabric/src/main/resources/config.yml

the config.yml in the fabric implementation is outdated and presumably unneeded
change 
project.

Fix fabric config

---

buildSrc/src/main/kotlin/DependencyConfig.kt

git is being bad so I'm just pring

git is being bad so I'm just pring

---

common/addons/config-noise-function/src/main/java/com/dfsek/terra/addons/noise/NoiseAddon.java
common/addons/config-noise-function/src/main/java/com/dfsek/terra/addons/noise/config/templates/normalizer/LinearMapNormalizerTemplate.java
common/addons/config-noise-function/src/main/java/com/dfsek/terra/addons/noise/normalizer/LinearMapNormalizer.java

Adds a linear map normalizer for mapping samplers from one range to another.
change 
project. 
I have not tested if this works as intended

Linear map normalizer

---

common/addons/config-noise-function/src/main/java/com/dfsek/terra/addons/noise/config/templates/noise/CellularNoiseTemplate.java
common/addons/config-noise-function/src/main/java/com/dfsek/terra/addons/noise/samplers/noise/CellularSampler.java

Allows lookup samplers to not be affected by the cellular sampler's salt
Only affects behavior if salting is explicitly turned off by setting `salt-lookup` to `false`
change 
project.

Add option to not salt cellular lookup

---

platforms/bukkit/common/src/main/java/com/dfsek/terra/bukkit/BukkitAddon.java
platforms/bukkit/common/src/main/java/com/dfsek/terra/bukkit/config/PreLoadCompatibilityOptions.java
platforms/bukkit/nms/v1_19_R1/src/main/java/com/dfsek/terra/bukkit/nms/v1_19_R1/NMSChunkGeneratorDelegate.java
platforms/bukkit/nms/v1_19_R1/src/main/java/com/dfsek/terra/bukkit/nms/v1_19_R1/Reflection.java

Implements beardification on Bukkit. Currently untested.
Closes #370

implement beardification on Bukkit (closes #370)

---

platforms/forge/src/main/java/com/dfsek/terra/forge/ForgePlatform.java

make froge compile so build work :)

make forge compile

---

common/addons/config-noise-function/build.gradle.kts
common/addons/config-noise-function/src/main/java/com/dfsek/terra/addons/noise/samplers/noise/CellularSampler.java

Adds a new return type to the cellular sampler, based on the offset of the coordinates relative to the cell center. More about this is in "Goal of the PR"
Currently there is no way to create terrain EQs with cells where the result is based on the position relative to the center. It is possible to do something similar by combining distance and angle samplers, but this will result in worse performance and confusion than this approach.
Minor addition to the cellular sampler in the noise functions plugin. Adds another return type which also uses the noioseLookup, but instead of sampling at the center of the cell, it passes the offset of the …

Add cell center offset return to CELLULAR sampler

---

common/addons/structure-terrascript-loader/src/main/java/com/dfsek/terra/addons/terrascript/script/builders/BlockFunctionBuilder.java
common/addons/structure-terrascript-loader/src/main/java/com/dfsek/terra/addons/terrascript/script/functions/BlockFunction.java
gradle.properties
platforms/bukkit/common/src/main/java/com/dfsek/terra/bukkit/util/BukkitUtils.java
platforms/bukkit/common/src/main/java/com/dfsek/terra/bukkit/world/BukkitProtoWorld.java
platforms/fabric/build.gradle.kts
platforms/fabric/src/main/java/com/dfsek/terra/fabric/FabricEntryPoint.java
platforms/fabric/src/main/java/com/dfsek/terra/fabric/FabricPlatform.java
platforms/forge/build.gradle.kts
platforms/mixin-common/src/main/java/com/dfsek/terra/mod/mixin/implementations/terra/chunk/WorldChunkMixin.java
platforms/mixin-lifecycle/build.gradle.kts
platforms/mixin-lifecycle/src/main/java/com/dfsek/terra/lifecycle/LifecycleEntryPoint.java
platforms/mixin-lifecycle/src/main/java/com/dfsek/terra/lifecycle/LifecyclePlatform.java
platforms/quilt/build.gradle.kts
platforms/quilt/src/main/java/com/dfsek/terra/quilt/QuiltEntryPoint.java
platforms/quilt/src/main/java/com/dfsek/terra/quilt/QuiltPlatform.java

Exposes the existing physics setblock api to terrascript
change 
project. 
do we even have tests?

Allows you to create a block with physics enabled

---

common/addons/config-number-predicate/build.gradle.kts
common/addons/config-number-predicate/src/main/java/com/dfsek/terra/addons/numberpredicate/DoublePredicateLoader.java
common/addons/config-number-predicate/src/main/java/com/dfsek/terra/addons/numberpredicate/NumberPredicateAddon.java
common/addons/config-number-predicate/src/main/resources/terra.addon.yml

Adds a loader for `java.util.function.DoublePredicate` that uses paralithic for evaluation. Uses `value` as an invocation variable representing the predicate input.
Example expression: `5 < value && value < 10` returns true for inputs between 5 and 10,
PR intends on adding a loader for use in #413
change 
project.

Add number predicate addon

---

common/addons/locator-slant-noise-3d/build.gradle.kts
common/addons/locator-slant-noise-3d/src/main/java/com/dfsek/terra/addon/feature/locator/slant/SlantLocator.java
common/addons/locator-slant-noise-3d/src/main/java/com/dfsek/terra/addon/feature/locator/slant/SlantLocatorAddon.java
common/addons/locator-slant-noise-3d/src/main/java/com/dfsek/terra/addon/feature/locator/slant/SlantLocatorTemplate.java
common/addons/locator-slant-noise-3d/src/main/resources/terra.addon.yml

PR adds the `SLANT` locator, which allows placement of features based on the slant value provided by the noise3d chunk generator. The config uses a `DoublePredicate`, a loader of which is provided by #412.
Example config:
```yaml
locator:
type: SLANT
condition: value > 5
```
change 
project.

Add slant locator

---

buildSrc/src/main/kotlin/DistributionConfig.kt
gradle.properties
platforms/fabric/build.gradle.kts
platforms/fabric/src/main/resources/fabric.mod.json

Ver/6.4.0 2: Electric Boogaloo

---

buildSrc/src/main/kotlin/DistributionConfig.kt

fix building

---

platforms/fabric/build.gradle.kts

We've had one, yes. What about second build issue?

---

common/addons/config-ore/build.gradle.kts
common/addons/config-ore/src/main/java/com/dfsek/terra/addons/ore/utils/VanillaOreUtils.java

Some users in discord have been reporting ore not being visible, have not inspected this in game yet due to dev launch being borked but going to assume reports are valid and the issue is caused by flipped method boolean return.

Invert exposed ore logic

---

buildSrc/src/main/kotlin/AddonConfig.kt
buildSrc/src/main/kotlin/DistributionConfig.kt
buildSrc/src/main/kotlin/Utils.kt
buildSrc/src/main/kotlin/com/dfsek/terra/tectonicdoc/GenerateDocsTask.kt
platforms/merged/build.gradle.kts
settings.gradle.kts

Replaces `println` calls with calls to Gradle loggers. The messages are set to log at `INFO`, which I believe won't show up by default, they seem to add a lot of noise when running tasks (subproject prints aren't really necessary to show all the time as `gradle projects` exists), but this can be up for discussion.

Use logger in Gradle over println

---

build.gradle.kts
buildSrc/src/main/kotlin/AddonConfig.kt
buildSrc/src/main/kotlin/DistributionConfig.kt
buildSrc/src/main/kotlin/Utils.kt
buildSrc/src/main/kotlin/com/dfsek/terra/tectonicdoc/GenerateDocsTask.kt
common/addons/config-ore/build.gradle.kts
common/addons/config-ore/src/main/java/com/dfsek/terra/addons/ore/utils/VanillaOreUtils.java
platforms/fabric/build.gradle.kts
platforms/merged/build.gradle.kts
settings.gradle.kts

Mainly just provides a bug fix for exposed ore behavior
- #434 
- #433 

Patch version /6.4.1

---

build.gradle.kts
common/addons/config-noise-function/src/main/java/com/dfsek/terra/addons/noise/samplers/noise/fractal/BrownianMotionSampler.java
common/addons/config-noise-function/src/main/java/com/dfsek/terra/addons/noise/samplers/noise/fractal/PingPongSampler.java
common/addons/config-noise-function/src/main/java/com/dfsek/terra/addons/noise/samplers/noise/fractal/RidgedFractalSampler.java
common/addons/config-noise-function/src/main/java/com/dfsek/terra/addons/noise/samplers/noise/simplex/PerlinSampler.java
common/addons/config-noise-function/src/main/java/com/dfsek/terra/addons/noise/samplers/noise/value/ValueSampler.java

Fixes critical issue with lerp in noise function addon

6.4.3 - Fix lerp (urgent)

---

common/addons/config-noise-function/src/main/java/com/dfsek/terra/addons/noise/samplers/noise/simplex/OpenSimplex2Sampler.java

Flip comparison

---

.gitmodules
buildSrc/src/main/kotlin/Versions.kt
platforms/allay/.gitignore
platforms/allay/build.gradle.kts

Downloads allay mappings from github.
Closes #492

Remove Allay Mappings Submodules

---

buildSrc/src/main/kotlin/Versions.kt
platforms/minestom/src/main/java/com/dfsek/terra/minestom/MinestomPlatform.java
platforms/minestom/src/main/java/com/dfsek/terra/minestom/biome/MinestomBiomeLoader.java
platforms/minestom/src/main/java/com/dfsek/terra/minestom/block/DefaultBlockEntityFactory.java
platforms/minestom/src/main/java/com/dfsek/terra/minestom/block/MinestomBlockEntity.java
platforms/minestom/src/main/java/com/dfsek/terra/minestom/block/MinestomBlockState.java
platforms/minestom/src/main/java/com/dfsek/terra/minestom/entity/MinestomEntityType.java
platforms/minestom/src/main/java/com/dfsek/terra/minestom/item/MinestomEnchantment.java
platforms/minestom/src/main/java/com/dfsek/terra/minestom/item/MinestomItemHandle.java
platforms/minestom/src/main/java/com/dfsek/terra/minestom/item/MinestomItemStack.java
platforms/minestom/src/main/java/com/dfsek/terra/minestom/item/MinestomMaterial.java
platforms/minestom/src/main/java/com/dfsek/terra/minestom/world/TerraMinestomWorldBuilder.java

Backports Minestom 1.21.6 Support from the 7.0 branch

feat: backport latest minestom support from 7.0 branch

---

platforms/bukkit/common/src/main/java/com/dfsek/terra/bukkit/PlatformImpl.java
platforms/bukkit/common/src/main/java/com/dfsek/terra/bukkit/hooks/MultiverseGeneratorPluginHook.java
platforms/bukkit/common/src/main/java/com/dfsek/terra/bukkit/listeners/CommonListener.java
platforms/bukkit/common/src/main/java/com/dfsek/terra/bukkit/world/BukkitBiomeInfo.java
platforms/bukkit/nms/v1_21_6/src/main/java/com/dfsek/terra/bukkit/nms/v1_21_6/AwfulBukkitHacks.java

Fixed wolf variant support for Paper platform

---

platforms/bukkit/common/src/main/java/com/dfsek/terra/bukkit/listeners/CommonListener.java

I noticed that wolves that spawned on chunk generation were not receiving the correct variants, this should now be resolved following this.

Made wolves generated with chunks correctly inherit variants

---

platforms/bukkit/common/src/main/java/com/dfsek/terra/bukkit/listeners/CommonListener.java

- Correctly applies wolf variant  to 'naturally' spawning wolves
- Adjusts the scope of the debug log

More wolf fixes
